### ISSUE TITLE
Building on ARM64

### ISSUE THREAD

**Issue by ismailkarsli** [raskyld/lemmy-cross-toolchains#2]
I'm using ARM PC and I can't build Lemmy ARM images with it :/ Is there a reason to not have this? Currently I'm emulating x64 device and using docker buildx to build ARM images.

**Comment by raskyld** [comment]
Hello Ismail, this toolchain is made to build Lemmy docker images on AMD host targeting ARM runners. Building Lemmy on ARM for ARM should be possible but you wouldn't need this (or any) toolchain for that. (cc @dessalines)

**Comment by ismailkarsli** [comment]
> Hello Ismail, this toolchain is made to build Lemmy docker images on AMD host targeting ARM runners. Building Lemmy on ARM for ARM should be possible but you wouldn't need this (or any) toolchain for that. (cc @dessalines)

Yeah, I also thought I could create an ARM image on ARM PC, but later I realized that the Dockerfile only works on AMD64. So if I strip the ARM64/AMD64 related parts in the Dockerfile and simplify it, it should supposed to work? I'll try it.

I guess this problem is not related with this repo. Thanks for the explanation.

**Comment by raskyld** [comment]
Yep, exactly.

If you look at this line: https://github.com/LemmyNet/lemmy/blob/0d35c247f9a5f1d866c0d0ae72f873bf13fc5006/docker/Dockerfile#L47

It uses this cross-toolchain because Lemmy maintainers only have access to AMD64 builder, so they need a cross-toolchain to compile on AMD64 **but targeting** ARM64.

In theory, you could instead use a arm64 image, for example, the official `rust` image there on your arm64 workstation :)

I hope this helps.
